spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Smarket?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username : ecommerce
    password: ecommerce
    #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  application :
    name : s-market
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
server:
  address: 172.25.224.1
  port: 8080

logging:
  level:
    jdbc:
      sqlonly : off
      sqltiming: debug
      resultsettable : off
      audit : off
      resultset : off
      connection : off