spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Smarket?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username : ecommerce
    password: ecommerce
  application :
    name : s-market
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true


