spring:
  # .env import
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username : ${DB_USERNAME}
    password: ${DB_PASSWORD}

  application :
    name : s-market

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  mail:
    host: smtp.naver.com
    port : ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PW}
    properties:
      mail.smtp.auth: true
      mail.smtp.enable : true
      mail.smtp.ssl.trust : smtp.naver.com

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  address: ${SERVER_HOST}
  port: ${SERVER_PORT}